### ISSUE TITLE
Yarn registry is down

### ISSUE THREAD

**Issue by parketh** [MetaMask/safe-event-emitter#134]
The yarn install link for v2.0.0 seems to be down, which is causing build errors for repos that use this library as a dependency:

https://registry.yarnpkg.com/@metamask/safe-event-emitter/-/safe-event-emitter-2.0.0.tgz

![Screenshot 2023-05-15 at 10 56 34](https://github.com/MetaMask/safe-event-emitter/assets/27808560/2cf6a5a2-a3f4-4975-ac45-1e358ec7e845)

**Comment by mcmire** [comment]
We didn't make Yarn, so as much as we'd like to address this issue, we can't :) You may want to [join the Yarn discord](https://discord.com/invite/yarnpkg) to see if you can get in touch with the maintainers or at least see what's going on.

That said, the link you posted seems to work for me which indicates that the registry is back up. Is it working for you too?

**Comment by parketh** [comment]
Yes, seems to be back up!
